### ISSUE TITLE
Ejecucion de ejemplos - pyreclab

### ISSUE THREAD

**Issue by ANDRESHZ** [PUC-RecSys-Class/RecSysPUC-2020#1]
una vez compiladas, construidas e instaladas para **python 3.8** de manera exitosa según lo indicado por la Terminal
obtuve y valoidado
`pip3 install pyreclab`

> Requirement already satisfied: pyreclab in ./anaconda3/lib/**python3.8**/site-packages/pyreclab-0.1.14-py3.8-linux-x86_64.egg (0.1.14)

permitiendo realizar la importación dentro de los programas de Python
al intentar correr cualquier ejemplo no encuentra los atributos puestos para el funcionamiento en ninguno de ellos: 
```
cd pyreclab/examples/
python3.8 testBprMf.py 
```

> Traceback (most recent call last):  File "testBprMf.py", line 6, in <module>    bprmf = pyreclab.BprMf( factors = 20, AttributeError: module 'pyreclab' has no attribute '_BprMf_'

`python3.8 testFunkSvd.py`
> Traceback (most recent call last):  File "testFunkSvd.py", line 6, in <module>    svd = pyreclab.SVD( factors = 1000,AttributeError: module 'pyreclab' has no attribute '_SVD_'
`python3.8 testIFAlsCg.py `
> Traceback (most recent call last):  File "testIFAlsCg.py", line 6, in <module>    ifalscg = pyreclab.IFAlsConjugateGradient( factors = 50,AttributeError: module 'pyreclab' has no attribute '_IFAlsConjugateGradient_'
`python3.8 testIFAls.py `

> Traceback (most recent call last):   File "testIFAls.py", line 6, in <module>    ifals = pyreclab.IFAls( factors = 50,AttributeError: module 'pyreclab' has no attribute '_IFAls_'

`python3.8 testItemAvg.py `

> Traceback (most recent call last):  File "testItemAvg.py", line 6, in <module>    iavg = pyreclab.ItemAvg( dataset = 'dataset/u1.base',AttributeError: module 'pyreclab' has no attribute '_ItemAvg_'

…
…
…
`python3.8 testUserKnn.py `

> Traceback (most recent call last):  File "testUserKnn.py", line 6, in <module>
>     ubknn = pyreclab.UserKnn( dataset = 'dataset/u1.base', AttributeError: module 'pyreclab' has no attribute '_UserKnn_

'

¿A alguno le ha pasado? Estoy en un ambiente local (Pues mi idea es poder replicar posteriormente sin COLAB)

**Comment by denisparra** [comment]
este issue es de pyreclab, es mejor dirigirlo directamente a @gasevi  en https://github.com/gasevi/pyreclab/issues

**Comment by ojedaf** [comment]
Estimados/as, 

Recomiendo mucho correr todo en google colab, presenta muchas ventajas para ustedes, es super fácil de usar y no van a utilizar los recursos de sus computadores e incluso tienen acceso a más recursos que el que seguro tienen en su computador personal. Ademas, el equipo de ayudantes ya ha probado todas las practicas en esta plataforma y aseguramos que funcionan. Para los que quieran seguir intentando de forma local, lo cual no lo recomiendo, tengan en cuenta que esta librería no funciona muy bien en windows, para los que tengan windows instalen ubuntu subsystem y manejen virtualenvs con python 3.7 (NO PYTHON 3.8).

Saludos, 
Andrés Villa

**Comment by Oisangui** [comment]
Me pasó lo mismo con python3.8, pero al instalarlo en python3.6 funciona sin problemas. Saludos.
