### ISSUE TITLE
[Tarea] Timestamp

### ISSUE THREAD

**Issue by ivaniadg** [PUC-RecSys-Class/RecSysPUC-2020#10]
Estuve explorando la columna timestamp para cada usuario. Calculé la diferencia entre el timestamp mayor y menor del conjunto de ítems de cada usuario y obtuve que en promedio están 0.5 segundos interactuando con las imágenes, como máximo 20 segundos y la mayoría tiene 0 segundos. Este es el código con el que lo calculé:

``` python
def get_time_range(df):
    return df['timestamp'].max() - df['timestamp'].min()

x = df.groupby('user_id').apply(get_time_range)
``` 
Pensaba que el timestamp indicaba que el usuario le había hecho click a la imagen. ¿Qué significa realmente? ¿Es el momento en que el usuario vio el ítem, le hizo click u otra cosa?

**Comment by mcartagenah** [comment]
Consulté y no puedo encontrar si en verdad ese timestamp está correlacionado con los tiempos que el usuario le dio like o agregó la imagen a un board.

Seguiré investigando y aviso cualquier cosa.

Saludos
