### ISSUE TITLE
Instalación pyreclab

### ISSUE THREAD

**Issue by Regenschrim** [PUC-RecSys-Class/RecSysPUC-2020#13]
Hola, por alguna extraña razón no puedo instalar pyreclab de forma local. Traté instalandoló desde la consola y desde un jupyter pero no hay caso, no sé que será. Además, me dice:

```
ERROR: Could not find a version that satisfies the requirement pyreclab (from versions: none)
ERROR: No matching distribution found for pyreclab
```

 Desde un colab no tengo problemas asi que trabajaré desde ahí por mientras.

Cualquier información útil se agradece!

**Comment by vgaraujov** [comment]
Redireccionado al issue #1 el cual parece ser un caso similar.
