### ISSUE TITLE
[Tarea] - Valores de MAP y nDCG

### ISSUE THREAD

**Issue by Jiruiz2** [PUC-RecSys-Class/RecSysPUC-2020#15]
Hola,

Estuvimos trabajando con ALS y BPR con mi grupo usando pyreclab y al momento de calcular el MAP y nDCG nos entrega 0.0 para ambos algoritmos y no sabemos si está bien o no.
Nuestra matriz tiene el user_id, item_id e iteracted. Esta última es una columna llena de 1's.

Saludos.

**Comment by mcartagenah** [comment]
Esto pasa no necesariamente porque el algoritmo haya sacado 0, sino que puede haber sido tan bajo que se aproximó a 0.
Por como dices que estás trabajando la matriz, parece estar bien. Puede que haya algún problema con tu división train/test, por ejemplo que en el test hayan usuarios que en train no, o lo mismo pero con items.

Saludos.

**Comment by FloValdes** [comment]
Hola, a nosotros nos pasaba lo mismo y lo arreglamos, no sé si sea el mismo problema pero quizás te sirva.

Usamos el código de la ayudantía para pasar a una sparse_matrix pero nos dimos cuenta de que pasaba a una matriz con el index del dato y el id_del usuario en vez de id_item, id_usuario. Cambiamos el código para que efectivamente sea una matriz con los items (para eso hay que cambiar los nombres de las imágenes a un id, porque no pueden ser strings para las matrices) y ahí nos dio algo más que 0.
