### ISSUE TITLE
[Tarea] Problema visualización de imágenes

### ISSUE THREAD

**Issue by vndiaz1** [PUC-RecSys-Class/RecSysPUC-2020#16]
Hola, traté de utilizar el link http://niebla.ing.puc.cl/iic3633-2020/ para ver las imágenes y me aparece el error 404 Not Found. Hoy día en clases escuché que no era el único que le pasaba, por lo que les quería pedir si lo pueden revisar.
Muchas gracias!

**Comment by mcartagenah** [comment]
¿De qué manera trataste de acceder?

Para ver una imagen en el server tienes que agregar el ID de la imagen al final de esa ruta, y lo que falto en el enunciado es que además hay que ponerle un .jpg al final del ID.

Por ejemplo:

https://niebla.ing.puc.cl/iic3633-2020/e29e422c743a3d39a45c2bf777cc7091.jpg

Saludos.

**Comment by vndiaz1** [comment]
Aaa ya ya perfecto! Eso me había faltado.
Gracias !!
