### ISSUE TITLE
[Tarea] Consulta ALS Tarea 1

### ISSUE THREAD

**Issue by apachaii** [PUC-RecSys-Class/RecSysPUC-2020#17]
Hola una consulta, realizando el practico de ALS , me queda una duda respecto a cómo tratar el dataset de la tarea,  en el practico se utilizan 3 dataset para entrenar el modelo (test,train,item), en clase el profesor nos explico como poder dividir el dataset de entrenamiento en uno de testint (considerando que el dataset de test es en realidad un conjunto de usuarios a predecir), sin embargo me queda la duda con item, por lo que he visto item en el practico es un conjunto de características de las películas, en nuestro caso no tenemos ese item de imágenes, mi duda es como adaptar ese imput al modelo, ¿creamos un dataset a partir de los item?, creo que me perdí un poco en esa parte, De antemano Gracias!

**Comment by mcartagenah** [comment]
El dataset de test debe tener la misma forma que el de train, nosotros en la tarea para poder armar una competencia tipo Kaggle, les dimos solo los user_id para que nos manden sus listas de recomendación para esos usuarios y nosotros calcular las métricas con un dataset de test propio.

Cuando dividas los datos que se te entregaron, debes hacer por ejemplo, un split 90-10 para train-test, procurando que los usuarios de test aparezcan en train al igual que los items, porque de otra forma con este tipo de algoritmo, no va a saber como recomendarles.

Saludos.

**Comment by apachaii** [comment]
entiendo, Gracias por la respuesta
