### ISSUE TITLE
[Tarea] Duda negative sampling

### ISSUE THREAD

**Issue by FloValdes** [PUC-RecSys-Class/RecSysPUC-2020#20]
Hola, no entiendo bien a qué se refiere con negative sampling, es la estrategia de bootstrap sampling que usa BPR?

Gracias.

**Comment by denisparra** [comment]
Es la estrategia de elegir el item "disliked" cuando armas las tripletas {u, i, j} (usuario, item liked, item disliked) y que en el paper BPR lo hacen completamente random.

**Comment by afcarvallo** [comment]
Hola, negative sampling consiste en escoger ejemplos negativos (con los que no ha interactuado usuario) para armar las tripletas (usuario, positivo, negativo) y así entrenar el modelo con BPR. Ya que si utilizamos todos los ejemplos con los que no interactúa el usuario sería demasiado ineficiente, por eso se hace una muestra. 
Respecto a la estrategia de bootstrap sampling, negative sampling no es una estrategia, la estrategia para escoger ejemplos negativos puede variar, se puede seleccionar de manera aleatoria o se pueden escoger ejemplos más difíciles, donde la distancia del ejemplo positivo al negativo sea pequeña. Al menos la que utiliza la librería implicit es aleatoria.

**Comment by FloValdes** [comment]
Entiendo, gracias!

**Comment by Jiruiz2** [comment]
Hola,

Como se aplicaría en este caso, tomando en cuenta que no tenemos items que no le gusten al usuario.

Saludos.

**Comment by afcarvallo** [comment]
Hola, en este caso los ítems con los que el usuario no ha interactuado se asume como que no le gustan.
