### ISSUE TITLE
Cambiar el learning rate

### ISSUE THREAD

**Issue by matiasop** [PUC-RecSys-Class/RecSysPUC-2020#21]
Creo que las funciones para ALS de la librería implicit y de pyreclab no permiten cambiar el learning rate. ¿Alguien sabe si hay alguna forma de cambiarlo?

**Comment by afcarvallo** [comment]
Hola, para ALS no hay learning rate por lo tanto no es necesario experimentar modificando ese parámetro. Gracias por la observación 👍 .

**Comment by matiasop** [comment]
Gracias

**Comment by denisparra** [comment]
Ojo eso sí: se pide usar ALS con gradiente conjugado https://github.com/gasevi/pyreclab#ifalscg , la versión de ALS normal puede ser muy lenta para un dataset muy grande
