### ISSUE TITLE
[Tarea] Uso de librería implicit

### ISSUE THREAD

**Issue by ivaniadg** [PUC-RecSys-Class/RecSysPUC-2020#25]
Hola :wave: 

Según el enunciado de la tarea no se puede usar la librería `implicit` para el algoritmo ALS. Cada vez que corría el algoritmo me daba como resultados puros ceros en MAP y ncdg, además de que demoraba ~15 minutos en entrenar. La librería `implicit` tiene un paramétro para usar gradiente conjugado y demora muy poco en entrenar (menos de un minuto por test). 
¿Es posible usar esta o debemos usar `pyreclab`?

**Comment by afcarvallo** [comment]
Hola, 
Si se puede ocupar la librería implicit, no es obligatorio usar solo pyreclab. 
Saludos!
