### ISSUE TITLE
[Tarea] Duda Informe

### ISSUE THREAD

**Issue by SarahEverke** [PUC-RecSys-Class/RecSysPUC-2020#26]
Hola,

¿es posible integrar el informe en el colab que tiene código? De esa forma es más fácil mostrar y explicar los resultados. 
Muchos saludos

**Comment by afcarvallo** [comment]
Hola, 
Lamentablemente no se puede porque dentro de los entregables tiene que estar el informe en pdf y el código.
Saludos!
