### ISSUE TITLE
Duda analisis de sensibilidad

### ISSUE THREAD

**Issue by ljrodriguez1** [PUC-RecSys-Class/RecSysPUC-2020#28]
Para hacer un análisis de sensibilidad mas completo ahora queremos usar gpu para entrenar.
esto nos trae el problema de que los factores latentes deben ser múltiplos de 32.

en el enunciado se pide entrenar para 50,100 y 200. puedo usar numeros cercanos a estos. para asi poder realizar el entrenamiento con gpu?

Saludos

**Comment by mcartagenah** [comment]
No veo problema, utiliza números similares y si quieres puedes agregar más valores.

**Comment by ljrodriguez1** [comment]
gracias!
