### ISSUE TITLE
Nuevo Plazo Tarea 1

### ISSUE THREAD

**Issue by mcartagenah** [PUC-RecSys-Class/RecSysPUC-2020#29]
Hola a tod@s,

Hubo gente que pidió que se diera más plazo para la tarea, así que decidimos darles hasta las 23:59 del Lunes 21 con tal de que igual puedan disfrutar tranquilos de las fiestas patrias y que terminen su tarea de la mejor manera.

Saludos,
Equipo RecSys 2020.

**Comment by denisparra** [comment]
Esta información es real. Saludos y felices fiestas.
