### ISSUE TITLE
[Proyecto][Propuesta] ¿Referencias se consideran en número de páginas?

### ISSUE THREAD

**Issue by ivaniadg** [PUC-RecSys-Class/RecSysPUC-2020#36]
Hola :wave: :wave: 

¿Las 2 o  3 páginas de la propuesta deben incluir las referencias?

**Comment by afcarvallo** [comment]
Hola, pueden agregar una página más de referencias (adicional a las 2 o 3 de la propuesta)

**Comment by ivaniadg** [comment]
Yay 🎉 gracias!
