### ISSUE TITLE
Lecturas semana 10

### ISSUE THREAD

**Issue by ivaniadg** [PUC-RecSys-Class/RecSysPUC-2020#41]
Hola :wave:

No han subido las lecturas que debemos entregar el lunes :eyes: ¿Me perdí de algo y no hay lecturas?

**Comment by denisparra** [comment]
este es el paper, pero se entregará la reseña en dos partes:

Zhang, S., Yao, L., Sun, A., & Tay, Y. (2019). Deep learning based recommender system: A survey and new perspectives. ACM Computing Surveys (CSUR), 52(1), 1-38.

- parte 1: entrega el viernes 23, hasta la sección 3.4 (inluyéndola)
- parte 2: entrega el viernes 30, desde sección 3.5 hasta el final

happy reading!
