### ISSUE TITLE
Fechas del Proyecto

### ISSUE THREAD

**Issue by ivaniadg** [PUC-RecSys-Class/RecSysPUC-2020#46]
Hola :wave: :wave: 

No sé si ya lo comentaron en clases (no pude estar en una de la semana pasada), pero tengo dos preguntas:

1. En la presentación de las evaluaciones dice que la fecha de entrega del proyecto es el 29 de noviembre pero dice por confirmar. ¿Sigue siendo la misma fecha? 
2. ¿Cuándo nos van a dar feedback sobre el avance que entregamos hace un par de semanas? Me interesa saber si hay algo que corregir lo antes posible.

Saludos :smile: :smile:

**Comment by denisparra** [comment]
Hola,

Estamos corrigiendo y empezaremos a enviar feedback durante la proxima semana, todos tendrán su feedback a más tardar Viernes 27 de noviembre.

Respecto a fechas: se envió un anuncio ayer desde canvas. Detalles aqui:
https://docs.google.com/presentation/d/1DkBNxdazzUH_UCo2ufBnvwA4nNuhHLKkthd_MJfc1VM/edit#slide=id.g1588ad92a4_0_18

Entrega final:
* Poster: Vi 11 Dic, 20:00 (en repo github del proyecto) 
Resto del proyecto: Lu 14 Dic, 20:00
Sesión de posters:
** Ma 15 Dic: via gather.town (8:30am - 1pm)
