### ISSUE TITLE
[Clases] Video clase jueves 13/8

### ISSUE THREAD

**Issue by ivaniadg** [PUC-RecSys-Class/RecSysPUC-2020#5]
Hola :wave: !
No está el link al video de la clase pasada en el syllabus. ¿Dónde puedo ver la clase :nerd_face: ?

**Comment by denisparra** [comment]
por el momento los videos de las clases estarán subidas en canvas. Muchos de los comentarios son muy asociados a temas internos del curso, por eso por el momento no estarán en el repositorio en github.

**Comment by denisparra** [comment]
ahora estoy subiendo los videos en un google drive asi es que están linkeados desde el repo también.

**Comment by denisparra** [comment]
![image](https://user-images.githubusercontent.com/208111/91462234-f6e19880-e857-11ea-8bdb-83cc6f7dbb4b.png)
